prabhupant/python-ds

useful_links.md

The description of Dynamic programming with Python examples.

Dynamic programing

---

useful_links.md

Really cool feature from Python 3.7 :)

A @dataclass tutorial

---

useful_links.md

Added links to 
1. Video lectures on youtube for DS & Algorithm by mycodeschool 
2. Introduction to Algorithms by Charles E. Leiserson, Clifford Stein, Ronald Rivest, and Thomas H. Cormen
3. Competitive Programming 3 (Handbook for ICPC and IOI contestants) 
4. Article on getting started with competitive coding

Added more resources to the repository

---

algorithms/strings/check_permutations.py

Added check permutations question from CTCI Q 1.2. Addresses #23

Added Check Permutations question from CTCI Q 1.2

---

data_structures/stack/Largest Rectangle area in a Histogram.py

I have added a stack implementation code for finding the max area rectangle of a given histogram

Added Largest area of rectangle in histogram in Stack

---

algorithms/dynamic_programming/index.md
algorithms/math/index.md
algorithms/sorting/index.md
data_structures/array/index.md
data_structures/binary_trees/index.md
data_structures/bst/index.md
data_structures/circular_linked_list/index.md
data_structures/doubly_linked_list/index.md
data_structures/graphs/index.md
data_structures/linked_list/index.md
data_structures/stack/index.md
data_structures/strings/index.md
index_updater.py

I added all the index.md as you say.
In addition I made a file called index_updater.py that generates those index.md.
Only you have to do is `./index_updater.py path`, for example: 
`./index_updater.py data`
If you want a different format for the markdown files tell me.
Have fun!

✨ Added. index.md per subfolder and updater script.

---

data_structures/strings/check_permutations.py

Adding a solution to check for permutations with a much better performance.

add additional solution by sorting letters

---

data_structures/stack/balanced_expression.py

Added implementation of checking if an expression is balanced using stack.

Determine if an expression is balanced using stack

---

algorithms/math/fibonacci_number.py

Calculate the nth Fibonacci Number of the Sequence

Nth Fibonacci Number of the Sequence

---

algorithms/sorting/bubble_sort.py

Open to refactoring comments for faster implementation.

Add Bubble Sort to algorithms/sorting

---

README.md
articles.md
books.md
misc.md
topics.md
tutorials.md
videos.md

Split useful_links.md into subfiles and add table of contents to README.md

---

algorithms/dynamic_programming/climbing_stairs.py
algorithms/dynamic_programming/edit_distance.py
algorithms/dynamic_programming/longest_common_subsequence.py
algorithms/dynamic_programming/max_subarray.py
algorithms/dynamic_programming/rod_cutting.py
algorithms/dynamic_programming/unique_grid_paths.py

The code style most be PEP8.
What do semicolon in python?

Fix code style. Remove two semicolon

---

data_structures/linked_list/merge_list_of_linked_lists.py

Recursively merge a list of sorted linked list into one sorted list containing all elements.

Merge list of sorted Linked Lists

---

data_structures/strings/adjacent_vowel_pairs.py

new question added in strings 
issue #23

new question added

---

algorithms/graph/bfs.py
algorithms/graph/dfs.py
algorithms/graph/index.md

Added Graph Algorithms

---

.theia/settings.json
algorithms/dynamic_programming/index.md
algorithms/greedy/index.md
algorithms/math/index.md
algorithms/miscellaneous/index.md
algorithms/sorting/index.md
data_structures/array/index.md
data_structures/binary_trees/index.md
data_structures/bst/index.md
data_structures/circular_linked_list/index.md
data_structures/doubly_linked_list/index.md
data_structures/graphs/index.md
data_structures/linked_list/index.md
data_structures/queue/index.md
data_structures/stack/index.md
data_structures/strings/index.md

Added index.md for sub-folders where not included and added links to all files within the sub-folder in index.md
Fixes #105

update and link files in index.md

---

algorithms/math/least_common_multiple.py

Add least_common_multiple

---

algorithms/miscellaneous/luhn_algorithm.py

Refactor luhn algorithm by adding docstring and tests.
Fixes # (#123)

Refactor luhn algo

---

algorithms/dynamic_programming/longest_palindromic_subsequence.py

Add longest_palindromic_subsequence to dynamic programming examples

Add longest_palindromic_subsequence

---

algorithms/greedy/dijkstra_greedy.py

added greedy algorithm dijsktra

Added dijsktra

---

data_structures/array/index.md
data_structures/array/rotation_simplified.py

Added Simplified array rotation algorithm. Added algorithm uses array slicing to simplify the code

Added Simplified array rotation algorithm

---

algorithms/sorting/heap_sort.py

Add heap sort to Algorithms folder

---

data_structures/binary_trees/binary-tree-level-order-traversal.py
data_structures/binary_trees/flatten-binary-tree-to-linked-list.py
data_structures/binary_trees/maximum-depth-of-binary-tree.py
data_structures/binary_trees/minimum-depth-of-binary-tree.py
data_structures/binary_trees/path-sum.py

Leetcode is a great platform for all tech interviews and has been suggested by big tech companies like Google. I have added solutions of few binary tree questions from leetcode.

Added binary tree leetcode questions

---

data_structures/strings/finding_all_substrings.py

I have added a question to display and count all substrings of a string in the strings module.
I humbly request you to review it :)
issue #23 
Checklist:

finding all substrings

---

data_structures/strings/roman_to_integer.py

Added code to convert a roman numeral to an integer given a string as input.
Fixes # 18

add roman to integer

---

data_structures/strings/one_away.py

Question from Cracking The Coding Interview which introduces edit distance (how "far" one string is from the other).
Addresses #23

Added One Away string question

---

index_updater.py

Explicitly added an exit code of 1 to index_updater.py.

explicitly add exit code of 1

---

algorithms/math/fibonacci_number.py
algorithms/math/greatest_common_divisor.py
algorithms/math/prime.py

Formatted the code to adhere to the guidelines of PEP 8.

fix PEP 8 issues

---

README.md

removed useful_links.md in the read.md file and added bookmarks directory

Minor changes added

---

algorithms/math/recursive_fibonacci.py

Added recursive function to compute the Fibonacci sequence.

Added recursive function to compute the Fibonacci sequence

---

algorithms/math/sumofdigits.py

Finding Sum off digits of a number untill the sum is singular,without any loops
Reducing the time Complexity of the program

Sumoffigitswithoutanyloop

---

algorithms/sorting/shell_sort.py

add code and comment shell_sort

---

data_structures/stack/stack_using_linked_list.py

This code implements stack using linked list instead of a normal Python list.
Fixes #18 

Implementation of stack using linked list

---

algorithms/sorting/insertion_sort.py

The existing code didn't sort a list. It always left the list unchanged.
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] My code follows the style guidelines of this project i.e. [Pep8](https://www.python.org/dev/peps/pep-0008/)
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have made corresponding changes to the documentation
- [  x ] Any dependent changes have been merged and published in downstream modules
- [ x ] I have squashed unnecessary commits

updated implementation, added basic usage demonstration

---

data_structures/union_find/uf.py

The Union-Find data structure was added to the data_structures folder along with proper documentation
Feature added

Added Union-Find data structure

---

data_structures/graphs/PrimsMST.py

Added Prim's Minimum Spanning Tree using adjacency matrix.
Addition to #17

Added Prim's MST to graph algorithms

---

.theia/settings.json

Removed theia

---

algorithms/sorting/pigeonhole_sort
algorithms/sorting/pigeonhole_sort.py

Issue #243 Resolved

---

data_structures/array/recurrentChar.py

print 1st recurrent character in str

---

data_structures/linked_list/merge_linked_list.py

The "merge" function in merge_linked_list.py was incomplete.  I updated it, making it match the working code in "merge_two_lists", from merge_list_of_linked_lists.py.  I also added some code at the end, demonstrating that the merge works as intended.
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the style guidelines of this project i.e. [Pep8](https://www.python.org/dev/peps/pep-0008/)
- [ x] I have performed a self-review of my own code

Use two list merge routine from merge_list_of_linked_lists.py

---

data_structures/array/find_odd_number.py

> Given an array, such as [0, 0, 1, 1, 2, 2, 6, 6, 9, 10, 10] where all numbers are duplicated twice, excluding one number, and I need to return the number that is not duplicated.
https://stackoverflow.com/questions/48675678/finding-the-odd-number-out-in-an-array
The best algorithm is to use **XOR** to find the odd number.
https://stackoverflow.com/a/48675962/482899

Find odd number in array

---

algorithms/math/index.md
algorithms/math/perfect_square.py

> In mathematics, a square number or perfect square is an integer that is the square of an integer;[1] in other words, it is the product of some integer with itself. For example, 9 is a square number, since it can be written as 3 × 3.

Perfect square

---

algorithms/dynamic_programming/dice.py

Added a new Dynamic Programming quesion.
Fixes #279 

Added a question in dynamic programming

---

algorithms/math/fibonacci_number.py

Fibonacci sequence was giving a syntax error, it's now fixed

Fixed fibonacci series

---

algorithms/sorting/select_sort.py

fixed pep8 issues

---

data_structures/strings/index.md
data_structures/strings/rotate_string.py

Given two strings, _A_ and _B_. A shift on _A_ consists of taking string _A_ and moving the leftmost character to the rightmost position. For example, if _A_ = 'abcde', then it will be 'bcdea' after one shift on _A_. Return True if and only if _A_ can become _B_ after some number of shifts on _A_.

Rotate string

---

data_structures/array/daysofweek.py

I have added a question regarding the days of the week

Added daysofweek.py

---

.theia/settings.json
algorithms/sorting/bubble_sort.py
algorithms/sorting/merge_sort.py

Fixed pep8 issues in two files. I should've included these changes in the PR I submitted earlier. Apologies.

fix: pep8 issues

---

data_structures/array/random_matrix.py

Generate random (n x n) matrix without repeated entries in rows or columns. The entries are integers between 1 and n.
The steps of algorithm:
1. Generate a shuffled list
1. Left rotated by 1 to generate the matrix
1. Shuffle rows in matrix
1. Shuffle cols in matrix (optional)
Ref: https://stackoverflow.com/a/56490787/482899

Random matrix without repeated entries in rows or columns

---

data_structures/bst/index.md

Removed an extra square bracket.

Updated data_structures/bst/index.md to remove typo

---

algorithms/dynamic_programming/bit_masking1.py
algorithms/dynamic_programming/k_palindrome1.py

Added Dynamic programming solution of a program using bit masking.
Added Optimal solution to find K-palindrome problem.

Bit Masking using Dynamic programming

---

data_structures/strings/check_interleaving_of_strings.py

Fixes #257

---

data_structures/array/index.md

I have added description to the question in array data structure except for few there was problem with those question so I will open issue for them 
Fixes #321 

added question description to array datastructure index.md

---

data_structures/graphs/Adjacency_matrix.py

Hi,
I have added the adjacency matrix to the graph folder. 

Adjacency matrix for graphs

---

CONTRIBUTING.md
README.md
notes.md

https://github.com/cclauss/python-ds/runs/468292827?check_suite_focus=true#step:6:7

Fix typos found by codespell

---

.github/workflows/lint_python.yml
algorithms/dynamic_programming/coin_change.py
algorithms/graph/dfs.py
algorithms/sorting/insertion_sort.py
data_structures/array/pivot_index.py
data_structures/bst/duplicate_keys.py
data_structures/bst/linked_list_to_bst.py
data_structures/bst/print_ancestor.py
data_structures/doubly_linked_list/doubly_linked_list.py
data_structures/linked_list/merge_linked_list.py
data_structures/matrix/flood_fill_algorithm.py
data_structures/stack/stack_using_linked_list.py

https://github.com/prabhupant/python-ds/actions
https://github.com/cclauss/python-ds/actions
https://flake8.pycqa.org/en/latest/user/error-codes.html
On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead these tests focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to Python 3.  These would be compile-time errors in a compiled language but in a dynamic language like Python they result in the script halting/crashing on the user.
* F63 tests are usually about the …

Add GitHub Action to lint Python code

---

algorithms/miscellaneous/front_and_back_search.py

This is a kind of linear search that looks for an item from either ends of an array.

Add front and back search

---

algorithms/math/index.md
algorithms/math/number_convertion.py

Create an algorithm to convert numbers from any base to any base.

add number conversion

---

algorithms/dynamic_programming/Z_Algorithm.py

I added new algorithm called Z_algorithm.
It can find all occurrences of some string s in text, with linear time with the help of dynamic programming.
Added new algorithm

Z_Algorithm

---

algorithms/dynamic_programming/longest_palindromic_substring.py

I added the Longest Palindromic Substring Question (with the expansionary method as well as the DP method)
Fixes # 340

Add Longest Palindromic Substring

---

data_structures/array/min_product.py

min_product was broken - variable name mismatch - fixed it. 
There was a variable name mismatch.
count_negative should have been used instead of count_neg.
Removed an unused variable.
Also fixes one of the lint checks.

min_product fix

---

algorithms/graph/mst.py

Add implementation of MST algorithm. Create class called Graph. 
Fixes #350
Checklist:

add implementation of MST algorithm

---

README.md
algorithms/bit_manipulation/range_sum_set_bits.py

I have:
- Create a category "Bit Manipulation" under algorithms.
- Added a solution to find the sum of number of set bits in the range [1, n].
- Specified an extension for the question along with its solution.
Fixes #354

Find the sum of number of set bits in a range of numbers

---

data_structures/strings/KMP_Pattern_Search.py

I have added the KMP Pattern Searching Algorithm in String.
Fixes #344 

KMP Pattern Searching Algorithm

---

algorithms/sorting/counting_sort.py

Adds an implementation of Counting sort.
Fixes #351 

add counting sort implementation

---

data_structures/linked_list/delete_last_occurrence.py
data_structures/linked_list/index.md
data_structures/stack/stack_using_list.py

Stack using list

---

data_structures/linked_list/delete_last_occurrence.py
data_structures/linked_list/index.md

Delete Last Occurrence of an element in a LinkedList

Delete last occurrence

---

data_structures/segment_tree/seg_tree_sum.py

Added new data structure. Segment Tree with sum queries.

SumSegTree

---

data_structures/segment_tree/seg_tree_max.py

New Data Structure. Segment Tree with Max queries.

MaxSegTree

---

algorithms/graph/dijkstra.py
algorithms/sorting/gnome_sort.py

Add dijkstra alghoritm implementation. I think its very important for graphs so i wanted to contribute it.
Fixes #359

add dijkstra alghoritm.

---

algorithms/dynamic_programming/prefix_function.py

Added prefix_function. The prefix function for string s is defined as an array pi of length n, where pi[i] is the length of the longest proper prefix of the substring s[0…i] which is also a suffix of this substring.

prefix_function added

---

algorithms/dynamic_programming/prefix_sums.py

prefix_sums added

---

data_structures/palindromic_tree/palindromic_tree.py

Add Palindromic_tree in data structures

---

algorithms/miscellaneous/markov.py

I have implemented markov chain algorithm for text generation. I look forward to comments!

markov chain algorithm

---

algorithms/dynamic_programming/hamilton_cycle.py

Dynamic solution for hamiltonian cycle in O(2^n*n) time and memory

hamilton dynamic solution for vertices <= 20 added

---

algorithms/math/recursive_fibonacci.py

TL;DR: I added a faster fibonacci-number-calculating algorithm.
In the previous version, recursive_fibonacci.py contained only the function rec_fib(n), which recursively calculates Fibonacci numbers using their recursive definition. However, this function gets extremely slow for large values of n. It requires O(Fibo(n)) operations, so the amount of time required actually grows exponentially (!!!). I added a new function called binary_rec_fib(n) that recursively calculates fibonacci numbers in O(n) time.

Binary-recursive Fibonacci function

---

.gitignore
algorithms/math/divisors.py

Natural number divisors and prime factors.

division factors

---

algorithms/math/factorial_iterative.py
algorithms/math/factorial_recursive.py
algorithms/math/index.md

Recursive and Iterative Factorial Solutions added.

Recursive and Iterative Factorial files added

---

index_updater.py

Changed the comment spelling
Comment had a spelling mistake
- Non-breaking change which fixes an issue of spelling

Spelling fix in index_updater.py

---

algorithms/math/greatest_common_divisor.py
index_updater.py

Added one module in GCD, that is optimized way to find gcd in iterative manner/
Addition of new module.

Gcd optimized branch

---

README.md

Made grammatical changes to make the documentation look more readable and appealing.

fixed spelling and grammatical errors to make the documentation look more readable.

---

algorithms/math/power_of_two.py

This simple code checks if a given number is a power of two or not.
Fixes #392

Check power of two

---

data_structures/array/max_product_three_elements.py

Added question and answer

---

algorithms/dynamic_programming/partition_sum.py

Added Partition Sum Problem in Dynamic Programming. 
Partition sum problem is to determine whether a given set can be partitioned into two subsets such that the sum of elements in both subsets is the same.
Idea behind the solution is to solve it in similar way as 0-1 knapsack problem, where there is a choice of taking elements such that 1 subset has a sum equal to half of the original set, then other half automatically has sum equal to this subset.

Added Partition Sum Problem

---

data_structures/array/permutations_of_word.py

I fixed a bug in /data_structures/array/permutations_of_word.py that caused the program to run into an error.
Fixes #430

Fixed a bug in /data_structures/array/permutations_of_word.py

---

data_structures/bst/average_of_levels.py

Added comments
